artifacts_root: "artifacts"

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Iv5kNzfdMLnIMkYwn0BAzbWhEH0damWT/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

# artifacts_root: "artifacts"

# data_ingestion:
#   root_dir: artifacts/data_ingestion
#   source_URL: https://drive.google.com/file/d/1Iv5kNzfdMLnIMkYwn0BAzbWhEH0damWT/view?usp=sharing
#   local_data_file: artifacts/data_ingestion/data.zip
#   unzip_dir: artifacts/data_ingestion

# prepare_base_model:  # Corrected indentation
#   root_dir: artifacts/prepare_base_model
#   base_model_path: artifacts/prepare_base_model/base_model.h5
#   updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3]  # as per VGG 16 model
# BATCH_SIZE: 16
# INCLUDE_TOP: False
# EPOCHS: 1
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.01